spring:
  application:
    name: faturamento
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: icompras-faturamento
      auto-offset-reset: earliest

icompras:
  config:
    kafka:
      topics:
        pedidos-pagos: "icompras.pedidos-pagos"
        pedidos-faturados: "icompras.pedidos-faturados"

server:
  port: 8084

minio:
  url: 'http://localhost:9000'
  access-key: minioadmin
  secret-key: minioadmin123
  bucket-name: icompras.faturas

#logging:
#  level:
#    org.springframework.kafka: DEBUG
#    org.apache.kafka: DEBUG
#    io.github.eduardopina.icompras.faturamento.subscribe: DEBUG
